#!/bin/bash

./for_coverage cargo +nightly test
grcov target/debug/ -s . -t lcov --llvm --branch --ignore-not-existing -o target/debug/lcov.info
genhtml -o cvg/ --show-details --highlight --ignore-errors source --legend target/debug/lcov.info
